include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .fvm/
    - .devcontainer/
    - .git/
    - .dart_tool/
    - build/
  errors:
    annotate_overrides: ignore
    overridden_fields: ignore

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_relative_imports: true
    depend_on_referenced_packages: false
