name: movitter
repository: https://github.com/wendellrocha/movitter
sdkPath: .fvm/flutter_sdk
packages:
  - packages/**

command:
  version:
    # Uses the pubspec_overrides.yaml instead of having Melos modifying the lock file.
    usePubspecOverrides: true
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
    # Prevents melos version from being used inside branches other than the one specified.
    branch: main
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  fix:
    run: melos exec -c 1 -- \
     dart fix --apply

  format:
    run: melos exec flutter format . --fix
    description: Run `flutter format` for all packages.

  format-check:
    run: melos exec flutter format . --set-exit-if-changed
    description: Run `flutter format` checks for all packages.
  
  clean:deep:
    run: git clean -x -d -f -q
    description: Clean things very deeply, can be used to establish "pristine checkout" status.

  test:
    run: echo "test ${TMDB_API_KEY}"

  qualitycheck:
    run: |
      melos run clean:deep && \
      melos clean && \
      melos bootstrap && \
      melos run lint:all
    description: Run all targets generally expected in CI for a full local quality check.

  get:
    run: fvm flutter pub get
    description: Run flutter pub get for main app.

  clean:
    run: fvm flutter clean
    description: Run flutter clean for main app.
    
  load:env:
    run: dart run scripts/environment_config.dart
    description: just loads .env values

  # Additional cleanup lifecycle script, executed when `melos clean` is run.
  postclean: melos exec -c 1 -- "flutter clean" && melos run clean
  postbootstrap: melos run get