name: modules
description: A new Flutter package project.
version: 0.0.1
publish_to: none
repository: https://github.com/wendellrocha/movitter/tree/main/packages/modules

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter_triple: ^1.2.7+2 # resolving slidy bad state: no element
  flutter:
    sdk: flutter
  common:
    path: '../common'
  dependencies:
    path: '../dependencies'
  rx_notifier: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
