name: common
description: A new Flutter package project.
version: 0.0.1
publish_to: none
repository: https://github.com/wendellrocha/movitter/tree/main/packages/common

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: '../dependencies'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
