name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  asuka: ^2.0.0+1
  dartz: ^0.10.1
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+2
  modular_triple_bind: ^1.0.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
